SCENARIO_WITHOUT_S_PAWNS = (
    "                 "
    "                 "
    "  N              "
    "  -*-            "
    " |               "
    " *               "
    " |               "
    "                 "
    "N       N        "
    "                 "
    "                 "
    "                 "
    "                 "
    "                 "
    "                 "
    "                 "
    "                 "
)

SCENARIO_WITHOUT_N_PAWNS = (
    "                 "
    "                 "
    "  S              "
    "  -*-            "
    " |               "
    " *               "
    " |               "
    "                 "
    "S       S        "
    "                 "
    "                 "
    "                 "
    "                 "
    "                 "
    "                 "
    "                 "
    "                 "
)


SCENARIO_WITH_BOTH_PAWNS = (
    "            N    "
    "                 "
    "                 "
    "  -*-            "
    " |               "
    " *               "
    " |    N          "
    "                 "
    "                 "
    "                 "
    "      S          "
    "                 "
    "        N   S    "
    "                 "
    "                 "
    "                 "
    "        S        "
)


SCENARIO_WITH_HORIZONTAL_WALLS = (
    "        N        "
    "                 "
    "                 "
    "      -*-   -*-  "
    "S               N"
    "                 "
    "  N              "
    "  -*-     -*-    "
    "                 "
    "      -*-        "
    "      S          "
    "  -*-     -*-    "
    "              S  "
    "-*-              "
    "                 "
    "                 "
    "                 "
)

SCENARIO_WITH_VERTICAL_WALLS = (
    "                 "
    "                 "
    "    N    |       "
    "         *       "
    "  S|     |    N  "
    "   *             "
    "   |   |N        "
    "       *         "
    "      S|       | "
    "               * "
    " |     |   |   | "
    " *     *   *     "
    " |   | |   |     "
    "     *           "
    "     |      S    "
    "                 "
    "                 "
) 

SCENARIO_WITH_BOTH_WALLS = (
    "                 "
    "                 "
    "      N  |       "
    "    -*-  *  -*-  "
    "S        |       "
    "                 "
    "       |         "
    "  -*-  *         "
    "    S  |    N  | "
    "               * "
    " |      N  |   | "
    " *    -*-  *     "
    " |         |     "
    "    -*-          "
    "              S  "
    "                 "
    "                 "

)

SCENARIO_WITHOUT_WALLS = (
    "                 "
    "                 "
    "  S              "
    "                 "
    "        N     S  "
    "                 "
    "                 "
    "                 "
    "        S        "
    "                 "
    "                 "
    "                 "
    "    N            "
    "                 "
    "            N    "
    "                 "
    "                 "
)

