name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run unit tests with pytest
      run: pytest
        